// ============================================
// PRODUCT DATA - NOW MANAGED IN DATABASE
// This file is kept for backwards compatibility
// All product data should be added via phpMyAdmin
// ============================================

const allProducts = [
    // Products will be loaded from MySQL database via API
    // To add products, use phpMyAdmin and insert into the 'products' table
    { id: 2, name: "Industrial Deck Oven", category: "baking-machines", price: 125000, oldPrice: null, image: "https://via.placeholder.com/300x300?text=Deck+Oven", description: "Commercial deck oven for bread and pastries", rating: 4.8, station: "new-arrivals" },
    { id: 3, name: "Planetary Mixer 20L", category: "baking-machines", price: 45000, oldPrice: 52000, image: "https://via.placeholder.com/300x300?text=Mixer+20L", description: "Heavy-duty planetary mixer for dough", rating: 4.6, station: "best-deals" },
    { id: 4, name: "Convection Oven", category: "baking-machines", price: 85000, oldPrice: null, image: "https://via.placeholder.com/300x300?text=Convection+Oven", description: "Electric convection oven with fan circulation", rating: 4.7, station: "pautang-deals" },
    { id: 5, name: "Bread Slicer Machine", category: "baking-machines", price: 32000, oldPrice: 38000, image: "https://via.placeholder.com/300x300?text=Bread+Slicer", description: "Automatic bread slicing machine", rating: 4.4, station: "all" },
    { id: 6, name: "Spiral Mixer 30L", category: "baking-machines", price: 95000, oldPrice: null, image: "https://via.placeholder.com/300x300?text=Spiral+Mixer", description: "Professional spiral mixer for bakery", rating: 4.9, station: "new-arrivals" },
    { id: 7, name: "Proofer Cabinet", category: "baking-machines", price: 65000, oldPrice: 75000, image: "https://via.placeholder.com/300x300?text=Proofer", description: "Temperature-controlled proofing cabinet", rating: 4.7, station: "best-deals" },
    { id: 8, name: "Donut Fryer", category: "baking-machines", price: 38000, oldPrice: null, image: "https://via.placeholder.com/300x300?text=Donut+Fryer", description: "Automatic donut frying machine", rating: 4.5, station: "pautang-deals" },
    { id: 9, name: "Pastry Display Chiller", category: "baking-machines", price: 75000, oldPrice: 82000, image: "https://via.placeholder.com/300x300?text=Display+Chiller", description: "Glass door pastry display refrigerator", rating: 4.8, station: "all" },
    { id: 10, name: "Pizza Oven Electric", category: "baking-machines", price: 55000, oldPrice: null, image: "https://via.placeholder.com/300x300?text=Pizza+Oven", description: "Electric pizza oven with stone deck", rating: 4.7, station: "all" },
    { id: 11, name: "Rotary Oven", category: "baking-machines", price: 185000, oldPrice: null, image: "https://via.placeholder.com/300x300?text=Rotary+Oven", description: "Industrial rotary rack oven", rating: 4.9, station: "new-arrivals" },
    { id: 12, name: "Steamer Gas 3-Tier", category: "baking-machines", price: 42000, oldPrice: null, image: "https://via.placeholder.com/300x300?text=Gas+Steamer", description: "3-tier gas-powered steamer", rating: 4.6, station: "pautang-deals" },
    { id: 13, name: "Dough Sheeter Electric", category: "baking-machines", price: 58000, oldPrice: 65000, image: "https://via.placeholder.com/300x300?text=Dough+Sheeter", description: "Electric dough sheeter for pastry", rating: 4.7, station: "best-deals" },
    { id: 14, name: "Cake Showcase", category: "baking-machines", price: 42000, oldPrice: null, image: "https://via.placeholder.com/300x300?text=Cake+Showcase", description: "Refrigerated cake display showcase", rating: 4.5, station: "all" },
    { id: 15, name: "Bread Oven Electric", category: "baking-machines", price: 68000, oldPrice: null, image: "https://via.placeholder.com/300x300?text=Bread+Oven", description: "Electric bread baking oven", rating: 4.6, station: "new-arrivals" },
    { id: 16, name: "Cookie Depositor", category: "baking-machines", price: 45000, oldPrice: 52000, image: "https://via.placeholder.com/300x300?text=Cookie+Depositor", description: "Automatic cookie depositing machine", rating: 4.4, station: "best-deals" },
    { id: 17, name: "Croissant Machine", category: "baking-machines", price: 78000, oldPrice: null, image: "https://via.placeholder.com/300x300?text=Croissant+Machine", description: "Automatic croissant rolling machine", rating: 4.7, station: "pautang-deals" },
    { id: 18, name: "Hot Dog Steamer", category: "baking-machines", price: 15000, oldPrice: 18000, image: "https://via.placeholder.com/300x300?text=Hotdog+Steamer", description: "Commercial hot dog steaming display", rating: 4.3, station: "all" },
    { id: 19, name: "Bun Steamer Electric", category: "baking-machines", price: 22000, oldPrice: null, image: "https://via.placeholder.com/300x300?text=Bun+Steamer", description: "Electric bun steaming cabinet", rating: 4.5, station: "new-arrivals" },
    { id: 20, name: "Crepe Maker", category: "baking-machines", price: 18000, oldPrice: 21000, image: "https://via.placeholder.com/300x300?text=Crepe+Maker", description: "Professional crepe making machine", rating: 4.4, station: "best-deals" },

    // PREPARATION & PROCESSING TOOLS - 20 products
    { id: 21, name: "Dough Divider", category: "preparation-tools", price: 42000, oldPrice: null, image: "https://via.placeholder.com/300x300?text=Dough+Divider", description: "Automatic dough dividing machine", rating: 4.6, station: "new-arrivals" },
    { id: 22, name: "Potato Peeler", category: "preparation-tools", price: 18000, oldPrice: 21000, image: "https://via.placeholder.com/300x300?text=Peeler", description: "Commercial potato peeling machine", rating: 4.4, station: "best-deals" },
    { id: 23, name: "Blender Heavy Duty", category: "preparation-tools", price: 12500, oldPrice: null, image: "https://via.placeholder.com/300x300?text=Blender", description: "Industrial blender 5L capacity", rating: 4.7, station: "pautang-deals" },
    { id: 24, name: "Food Processor 12L", category: "preparation-tools", price: 28000, oldPrice: 32000, image: "https://via.placeholder.com/300x300?text=Food+Processor", description: "Multi-function food processor", rating: 4.3, station: "best-deals" },
    { id: 25, name: "Meat Grinder", category: "preparation-tools", price: 18500, oldPrice: null, image: "https://via.placeholder.com/300x300?text=Meat+Grinder", description: "Heavy-duty meat grinder", rating: 4.6, station: "all" },
    { id: 26, name: "Vegetable Cutter", category: "preparation-tools", price: 15000, oldPrice: 18000, image: "https://via.placeholder.com/300x300?text=Vegetable+Cutter", description: "Multi-blade vegetable cutter", rating: 4.2, station: "pautang-deals" },
    { id: 27, name: "Electric Mixer 10L", category: "preparation-tools", price: 22000, oldPrice: null, image: "https://via.placeholder.com/300x300?text=Mixer+10L", description: "Electric stand mixer for baking", rating: 4.4, station: "all" },
    { id: 28, name: "Bread Molder", category: "preparation-tools", price: 35000, oldPrice: 39000, image: "https://via.placeholder.com/300x300?text=Bread+Molder", description: "Automatic bread molding machine", rating: 4.6, station: "all" },
    { id: 29, name: "Slicer Electric", category: "preparation-tools", price: 22000, oldPrice: 25000, image: "https://via.placeholder.com/300x300?text=Slicer", description: "Electric meat and cheese slicer", rating: 4.5, station: "all" },
    { id: 30, name: "Can Opener Electric", category: "preparation-tools", price: 3500, oldPrice: 4000, image: "https://via.placeholder.com/300x300?text=Can+Opener", description: "Commercial electric can opener", rating: 4.3, station: "all" },
    { id: 31, name: "Ice Crusher Machine", category: "preparation-tools", price: 8500, oldPrice: null, image: "https://via.placeholder.com/300x300?text=Ice+Crusher", description: "Heavy-duty ice crushing machine", rating: 4.5, station: "new-arrivals" },
    { id: 32, name: "Juicer Commercial", category: "preparation-tools", price: 15000, oldPrice: 17000, image: "https://via.placeholder.com/300x300?text=Juicer", description: "Commercial orange juicer", rating: 4.6, station: "best-deals" },
    { id: 33, name: "Noodle Maker", category: "preparation-tools", price: 12000, oldPrice: null, image: "https://via.placeholder.com/300x300?text=Noodle+Maker", description: "Electric noodle making machine", rating: 4.4, station: "pautang-deals" },
    { id: 34, name: "Rice Washer", category: "preparation-tools", price: 8000, oldPrice: 9500, image: "https://via.placeholder.com/300x300?text=Rice+Washer", description: "Automatic rice washing machine", rating: 4.3, station: "all" },
    { id: 35, name: "Garlic Peeler", category: "preparation-tools", price: 5500, oldPrice: null, image: "https://via.placeholder.com/300x300?text=Garlic+Peeler", description: "Electric garlic peeling machine", rating: 4.2, station: "new-arrivals" },
    { id: 36, name: "Dough Roller", category: "preparation-tools", price: 18000, oldPrice: 21000, image: "https://via.placeholder.com/300x300?text=Dough+Roller", description: "Countertop dough rolling machine", rating: 4.5, station: "best-deals" },
    { id: 37, name: "Egg Beater Electric", category: "preparation-tools", price: 6500, oldPrice: null, image: "https://via.placeholder.com/300x300?text=Egg+Beater", description: "Heavy-duty electric egg beater", rating: 4.4, station: "pautang-deals" },
    { id: 38, name: "Coconut Scraper", category: "preparation-tools", price: 7500, oldPrice: 8500, image: "https://via.placeholder.com/300x300?text=Coconut+Scraper", description: "Electric coconut scraping machine", rating: 4.3, station: "all" },
    { id: 39, name: "Batter Mixer", category: "preparation-tools", price: 14000, oldPrice: null, image: "https://via.placeholder.com/300x300?text=Batter+Mixer", description: "Commercial batter mixing machine", rating: 4.6, station: "new-arrivals" },
    { id: 40, name: "Dumpling Maker", category: "preparation-tools", price: 25000, oldPrice: 28000, image: "https://via.placeholder.com/300x300?text=Dumpling+Maker", description: "Automatic dumpling making machine", rating: 4.7, station: "best-deals" },

    // MEASURING & WEIGHING TOOLS - 10 products
    { id: 41, name: "Digital Scale 30kg", category: "measuring-tools", price: 3500, oldPrice: null, image: "https://via.placeholder.com/300x300?text=Digital+Scale", description: "Precision digital weighing scale", rating: 4.7, station: "new-arrivals" },
    { id: 42, name: "Measuring Cup Set", category: "measuring-tools", price: 850, oldPrice: 1200, image: "https://via.placeholder.com/300x300?text=Measuring+Cups", description: "Stainless steel measuring cup set", rating: 4.5, station: "best-deals" },
    { id: 43, name: "Kitchen Timer Digital", category: "measuring-tools", price: 450, oldPrice: null, image: "https://via.placeholder.com/300x300?text=Timer", description: "Digital countdown timer", rating: 4.3, station: "all" },
    { id: 44, name: "Thermometer Infrared", category: "measuring-tools", price: 1800, oldPrice: 2200, image: "https://via.placeholder.com/300x300?text=Thermometer", description: "Non-contact infrared thermometer", rating: 4.6, station: "pautang-deals" },
    { id: 45, name: "Platform Scale 150kg", category: "measuring-tools", price: 12500, oldPrice: null, image: "https://via.placeholder.com/300x300?text=Platform+Scale", description: "Heavy-duty platform weighing scale", rating: 4.8, station: "all" },
    { id: 46, name: "Portion Scale 5kg", category: "measuring-tools", price: 2800, oldPrice: null, image: "https://via.placeholder.com/300x300?text=Portion+Scale", description: "Compact portion control scale", rating: 4.5, station: "new-arrivals" },
    { id: 47, name: "Measuring Spoon Set", category: "measuring-tools", price: 350, oldPrice: 450, image: "https://via.placeholder.com/300x300?text=Spoons", description: "Stainless steel measuring spoons", rating: 4.3, station: "best-deals" },
    { id: 48, name: "Scale Hanging 50kg", category: "measuring-tools", price: 1500, oldPrice: null, image: "https://via.placeholder.com/300x300?text=Hanging+Scale", description: "Heavy-duty hanging scale", rating: 4.3, station: "all" },
    { id: 49, name: "Thermometer Oven", category: "measuring-tools", price: 650, oldPrice: null, image: "https://via.placeholder.com/300x300?text=Oven+Thermo", description: "Oven-safe thermometer", rating: 4.4, station: "all" },
    { id: 50, name: "Timer Mechanical", category: "measuring-tools", price: 250, oldPrice: null, image: "https://via.placeholder.com/300x300?text=Mech+Timer", description: "Wind-up mechanical kitchen timer", rating: 4.1, station: "all" },

    // GAS & POWER SUPPLY - 10 products
    { id: 51, name: "Gas Range 4 Burner", category: "gas-power", price: 35000, oldPrice: null, image: "https://via.placeholder.com/300x300?text=Gas+Range", description: "Commercial gas range with 4 burners", rating: 4.7, station: "new-arrivals" },
    { id: 52, name: "LPG Regulator", category: "gas-power", price: 850, oldPrice: 1000, image: "https://via.placeholder.com/300x300?text=Regulator", description: "High-pressure LPG regulator", rating: 4.4, station: "best-deals" },
    { id: 53, name: "Gas Hose 2 meters", category: "gas-power", price: 350, oldPrice: null, image: "https://via.placeholder.com/300x300?text=Gas+Hose", description: "Flexible gas hose connector", rating: 4.2, station: "all" },
    { id: 54, name: "Power Generator 5KVA", category: "gas-power", price: 45000, oldPrice: 52000, image: "https://via.placeholder.com/300x300?text=Generator", description: "Gasoline power generator", rating: 4.6, station: "pautang-deals" },
    { id: 55, name: "Voltage Stabilizer", category: "gas-power", price: 8500, oldPrice: null, image: "https://via.placeholder.com/300x300?text=Stabilizer", description: "Automatic voltage regulator", rating: 4.5, station: "all" },
    { id: 56, name: "Gas Leak Detector", category: "gas-power", price: 2500, oldPrice: null, image: "https://via.placeholder.com/300x300?text=Detector", description: "Portable gas leak detector", rating: 4.6, station: "pautang-deals" },
    { id: 57, name: "Burner Single Gas", category: "gas-power", price: 3500, oldPrice: 4000, image: "https://via.placeholder.com/300x300?text=Gas+Burner", description: "High-pressure single gas burner", rating: 4.5, station: "all" },
    { id: 58, name: "Extension Cord Heavy", category: "gas-power", price: 1200, oldPrice: 1400, image: "https://via.placeholder.com/300x300?text=Extension", description: "Heavy-duty 10-meter extension cord", rating: 4.5, station: "all" },
    { id: 59, name: "Circuit Breaker", category: "gas-power", price: 1500, oldPrice: null, image: "https://via.placeholder.com/300x300?text=Circuit+Breaker", description: "Automatic circuit breaker 50A", rating: 4.4, station: "new-arrivals" },
    { id: 60, name: "Gas Burner 2-Burner", category: "gas-power", price: 5500, oldPrice: 6200, image: "https://via.placeholder.com/300x300?text=2Burner", description: "Double burner gas stove", rating: 4.6, station: "best-deals" },

    // BAKING TRAYS & STORAGE - 10 products
    { id: 61, name: "Aluminum Baking Tray Set", category: "trays-storage", price: 2500, oldPrice: null, image: "https://via.placeholder.com/300x300?text=Baking+Trays", description: "Set of 5 aluminum baking trays", rating: 4.6, station: "new-arrivals" },
    { id: 62, name: "Stainless Steel Rack", category: "trays-storage", price: 4500, oldPrice: 5200, image: "https://via.placeholder.com/300x300?text=Steel+Rack", description: "5-tier stainless steel storage rack", rating: 4.7, station: "best-deals" },
    { id: 63, name: "Food Storage Container Set", category: "trays-storage", price: 1800, oldPrice: null, image: "https://via.placeholder.com/300x300?text=Containers", description: "Airtight food storage containers", rating: 4.4, station: "all" },
    { id: 64, name: "Bread Proofing Box", category: "trays-storage", price: 8500, oldPrice: 9800, image: "https://via.placeholder.com/300x300?text=Proofing+Box", description: "Commercial bread proofing cabinet", rating: 4.8, station: "pautang-deals" },
    { id: 65, name: "Cooling Rack Wire", category: "trays-storage", price: 650, oldPrice: null, image: "https://via.placeholder.com/300x300?text=Cooling+Rack", description: "Stainless steel cooling rack", rating: 4.3, station: "all" },
    { id: 66, name: "Sheet Pan Aluminum", category: "trays-storage", price: 850, oldPrice: null, image: "https://via.placeholder.com/300x300?text=Sheet+Pan", description: "Commercial aluminum sheet pan", rating: 4.4, station: "new-arrivals" },
    { id: 67, name: "Work Table Stainless", category: "trays-storage", price: 12500, oldPrice: 14000, image: "https://via.placeholder.com/300x300?text=Work+Table", description: "Commercial stainless steel work table", rating: 4.8, station: "all" },
    { id: 68, name: "Plastic Food Bins", category: "trays-storage", price: 2200, oldPrice: null, image: "https://via.placeholder.com/300x300?text=Food+Bins", description: "Set of 6 stackable food storage bins", rating: 4.4, station: "all" },
    { id: 69, name: "Dough Box Plastic", category: "trays-storage", price: 850, oldPrice: null, image: "https://via.placeholder.com/300x300?text=Dough+Box", description: "Stackable dough rising box", rating: 4.3, station: "all" },
    { id: 70, name: "Cake Pan Set", category: "trays-storage", price: 1500, oldPrice: 1800, image: "https://via.placeholder.com/300x300?text=Cake+Pans", description: "Non-stick cake pan set 6-piece", rating: 4.5, station: "best-deals" },

    // UTENSILS & ACCESSORIES - 10 products
    { id: 71, name: "Whisk Set Professional", category: "utensils", price: 1200, oldPrice: null, image: "https://via.placeholder.com/300x300?text=Whisk+Set", description: "Professional stainless steel whisk set", rating: 4.5, station: "new-arrivals" },
    { id: 72, name: "Silicone Spatula Set", category: "utensils", price: 850, oldPrice: 1100, image: "https://via.placeholder.com/300x300?text=Spatulas", description: "Heat-resistant silicone spatulas", rating: 4.6, station: "best-deals" },
    { id: 73, name: "Rolling Pin Stainless", category: "utensils", price: 950, oldPrice: null, image: "https://via.placeholder.com/300x300?text=Rolling+Pin", description: "Adjustable stainless steel rolling pin", rating: 4.4, station: "all" },
    { id: 74, name: "Pastry Brush Set", category: "utensils", price: 450, oldPrice: 600, image: "https://via.placeholder.com/300x300?text=Pastry+Brush", description: "Silicone pastry brush set", rating: 4.3, station: "pautang-deals" },
    { id: 75, name: "Chef Knife Set", category: "utensils", price: 3500, oldPrice: null, image: "https://via.placeholder.com/300x300?text=Knife+Set", description: "Professional chef knife collection", rating: 4.8, station: "all" },
    { id: 76, name: "Mixing Bowl Set", category: "utensils", price: 1500, oldPrice: 1800, image: "https://via.placeholder.com/300x300?text=Bowls", description: "Stainless steel mixing bowls 5-piece", rating: 4.6, station: "best-deals" },
    { id: 77, name: "Ladle Set Stainless", category: "utensils", price: 750, oldPrice: 900, image: "https://via.placeholder.com/300x300?text=Ladles", description: "Professional ladle set 3-piece", rating: 4.3, station: "all" },
    { id: 78, name: "Tongs Stainless", category: "utensils", price: 350, oldPrice: 450, image: "https://via.placeholder.com/300x300?text=Tongs", description: "Professional kitchen tongs set", rating: 4.4, station: "all" },
    { id: 79, name: "Oven Mitts Professional", category: "utensils", price: 650, oldPrice: null, image: "https://via.placeholder.com/300x300?text=Oven+Mitts", description: "Heat-resistant oven gloves pair", rating: 4.4, station: "all" },
    { id: 80, name: "Bread Knife Serrated", category: "utensils", price: 850, oldPrice: null, image: "https://via.placeholder.com/300x300?text=Bread+Knife", description: "Professional serrated bread knife", rating: 4.6, station: "all" },

    // INGREDIENTS & RAW MATERIALS - 10 products (spread across stations)
    { id: 81, name: "Bread Flour 25kg", category: "ingredients", price: 1850, oldPrice: null, image: "https://via.placeholder.com/300x300?text=Bread+Flour", description: "High-protein bread flour", rating: 4.7, station: "new-arrivals" },
    { id: 82, name: "Sugar White 50kg", category: "ingredients", price: 2500, oldPrice: 2800, image: "https://via.placeholder.com/300x300?text=Sugar", description: "Refined white sugar bulk pack", rating: 4.5, station: "best-deals" },
    { id: 83, name: "Butter Unsalted 1kg", category: "ingredients", price: 450, oldPrice: null, image: "https://via.placeholder.com/300x300?text=Butter", description: "Premium unsalted butter", rating: 4.6, station: "all" },
    { id: 84, name: "Yeast Instant 500g", category: "ingredients", price: 350, oldPrice: 420, image: "https://via.placeholder.com/300x300?text=Yeast", description: "Instant dry yeast for baking", rating: 4.8, station: "pautang-deals" },
    { id: 85, name: "Chocolate Chips 1kg", category: "ingredients", price: 650, oldPrice: null, image: "https://via.placeholder.com/300x300?text=Choco+Chips", description: "Premium chocolate chips", rating: 4.4, station: "all" },
    { id: 86, name: "All-Purpose Flour 25kg", category: "ingredients", price: 1650, oldPrice: null, image: "https://via.placeholder.com/300x300?text=AP+Flour", description: "Multi-purpose baking flour", rating: 4.5, station: "pautang-deals" },
    { id: 87, name: "Baking Powder 1kg", category: "ingredients", price: 280, oldPrice: 350, image: "https://via.placeholder.com/300x300?text=Baking+Powder", description: "Double-acting baking powder", rating: 4.5, station: "all" },
    { id: 88, name: "Cocoa Powder 1kg", category: "ingredients", price: 550, oldPrice: null, image: "https://via.placeholder.com/300x300?text=Cocoa", description: "Premium cocoa powder for baking", rating: 4.7, station: "all" },
    { id: 89, name: "Vanilla Extract 500ml", category: "ingredients", price: 850, oldPrice: null, image: "https://via.placeholder.com/300x300?text=Vanilla", description: "Pure vanilla extract", rating: 4.8, station: "all" },
    { id: 90, name: "Salt Iodized 25kg", category: "ingredients", price: 850, oldPrice: 1000, image: "https://via.placeholder.com/300x300?text=Salt", description: "Iodized table salt bulk", rating: 4.3, station: "best-deals" },

    // CLEANING & MAINTENANCE TOOLS - 10 products
    { id: 91, name: "Stainless Cleaner Spray", category: "cleaning", price: 350, oldPrice: null, image: "https://via.placeholder.com/300x300?text=Cleaner", description: "Stainless steel cleaner and polish", rating: 4.5, station: "new-arrivals" },
    { id: 92, name: "Scrub Brush Set", category: "cleaning", price: 450, oldPrice: 550, image: "https://via.placeholder.com/300x300?text=Brushes", description: "Heavy-duty cleaning brush set", rating: 4.3, station: "best-deals" },
    { id: 93, name: "Sanitizer Spray 5L", category: "cleaning", price: 1200, oldPrice: null, image: "https://via.placeholder.com/300x300?text=Sanitizer", description: "Food-safe sanitizer solution", rating: 4.7, station: "all" },
    { id: 94, name: "Microfiber Cloth Pack", category: "cleaning", price: 350, oldPrice: 450, image: "https://via.placeholder.com/300x300?text=Cloths", description: "Microfiber cleaning cloths 10-pack", rating: 4.4, station: "pautang-deals" },
    { id: 95, name: "Oven Cleaner Heavy Duty", category: "cleaning", price: 550, oldPrice: null, image: "https://via.placeholder.com/300x300?text=Oven+Cleaner", description: "Professional oven degreaser", rating: 4.6, station: "all" },
    { id: 96, name: "Degreaser Industrial", category: "cleaning", price: 850, oldPrice: null, image: "https://via.placeholder.com/300x300?text=Degreaser", description: "Heavy-duty kitchen degreaser", rating: 4.7, station: "new-arrivals" },
    { id: 97, name: "Mop and Bucket Set", category: "cleaning", price: 1200, oldPrice: 1500, image: "https://via.placeholder.com/300x300?text=Mop+Set", description: "Commercial mop and bucket system", rating: 4.4, station: "best-deals" },
    { id: 98, name: "Disinfectant 5L", category: "cleaning", price: 950, oldPrice: null, image: "https://via.placeholder.com/300x300?text=Disinfectant", description: "Food-grade disinfectant solution", rating: 4.6, station: "all" },
    { id: 99, name: "Floor Squeegee", category: "cleaning", price: 450, oldPrice: 550, image: "https://via.placeholder.com/300x300?text=Squeegee", description: "Heavy-duty floor water squeegee", rating: 4.2, station: "all" },
    { id: 100, name: "Trash Can 50L", category: "cleaning", price: 1500, oldPrice: 1700, image: "https://via.placeholder.com/300x300?text=Trash+Can", description: "Stainless steel pedal trash can", rating: 4.5, station: "all" }
];
